version: "3"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    command: [server, /data]
    volumes:
      - ~/docker/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: access_secret
    restart: always
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
